spring:
  profiles:
    active: test

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalab

  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/hide?serverTimezone=Asia/Seoul&characterEncoding=utf-8
     username: root
     password: so.jeoung

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          id:
            new_generator_mappings: true

  mail:
    host: smtp.naver.com
    port: 465
    username: groom_hide@naver.com
    password: groom_hide123
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
          starttls:
            enable: true