server:
  port: 8088

spring:
  profiles:
    active: test

  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: ${SPRING_DATASOURCE_URL}
     username: ${SPRING_DATASOURCE_USERNAME}
     password: ${SPRING_DATASOURCE_PASSWORD}
#    url: jdbc:mysql://mysql-container:3306/test
#    username: root
#    password: so.jeoung

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          id:
            new_generator_mappings: true